name: CI/CD MLflow Tebu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  xlx_url: "CI/data_train.xlsx"
  target: "Ton"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      - name: Setup MLflow Environment
        run: |
          mkdir -p CI/mlruns
          chmod -R 777 CI/mlruns
          echo "MLFLOW_TRACKING_URI=file://$(pwd)/CI/mlruns" >> $GITHUB_ENV
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn openpyxl
      
      - name: Verify Files Exist
        working-directory: ./CI
        run: |
          ls -la
          test -f data_train.xlsx || (echo "Data train not found!" && exit 1)
          test -f testing.xlsx || (echo "Testing data not found!" && exit 1)
          test -f preprocessing.py || (echo "Preprocessing script not found!" && exit 1)
      
      - name: Run mlflow project
        working-directory: ./CI
        run: |
          mlflow run . --env-manager=local || (echo "MLflow run failed!" && exit 1)
      
      - name: Get latest MLflow run_id
        id: get_run_id
        working-directory: ./CI
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | awk -F'/' '{print $3}')
          echo "run_id=${RUN_ID}" >> $GITHUB_OUTPUT
          echo "Latest run_id: ${RUN_ID}"
      
      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/${{ steps.get_run_id.outputs.run_id }}/model" --name sugarcane-model

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag and Push Docker Image
        run: |
          docker tag sugarcane-model ${{ secrets.DOCKER_HUB_USERNAME }}/sugarcane:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/sugarcane:latest
