name: CI/CD MLflow Tebu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "CI/data_train.xlsx"
  TARGET_VAR: "Ton"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          echo "CSV_URL: $CSV_URL"
          echo "TARGET_VAR: $TARGET_VAR"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn openpyxl pandas numpy joblib

      - name: Run mlflow project
        run: |
          mlflow run CI --env-manager=local

      - name: Get latest MLflow run_id
        id: get-run-id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/${{ env.RUN_ID }}/model" --name "sugarcane"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag and Push Docker Image
        run: |
          docker tag sugarcane ${{ secrets.DOCKER_HUB_USERNAME }}/sugarcane:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/sugarcane:latest
