name: CI/CD MLflow Tebu

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CSV_URL: "CI/data_train.xlsx"
  TARGET_VAR: "Ton"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas numpy openpyxl joblib

      - name: Start MLflow Tracking Server
        run: |
          nohup mlflow server \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root ./mlruns \
            --host 127.0.0.1 \
            --port 5000 > mlflow.log 2>&1 &
          sleep 10
        shell: bash

      - name: Set MLflow Tracking URI
        run: echo "MLFLOW_TRACKING_URI=http://127.0.0.1:5000" >> $GITHUB_ENV

      - name: Run MLflow Project
        run: |
          cd CI
          mlflow run . --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"
          
      # Build Docker Model
      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "sugarcane" 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag and Push Docker Image
        run: |
          docker tag sugarcane ${{ secrets.DOCKER_HUB_USERNAME }}/sugarcane:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/sugarcane:latest
