name: CI/CD MLflow Tebu

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set MLflow Local Tracking URI
        run: |
          mkdir -p CI/mlruns
          echo "MLFLOW_TRACKING_URI=file://$(pwd)/CI/mlruns" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow pandas scikit-learn openpyxl

      - name: Verify files exist
        working-directory: ./CI
        run: |
          ls -la
          test -f MLproject || (echo "Missing MLproject" && exit 1)
          test -f modeling.py || (echo "Missing modeling.py" && exit 1)
          test -f data_train.xlsx || (echo "Missing data" && exit 1)
          test -f testing.xlsx || (echo "Missing testing data" && exit 1)

      - name: Run MLflow project
        working-directory: ./CI
        run: |
          mlflow run . --env-manager=local

      - name: Get latest run ID
        id: get_run_id
        working-directory: ./CI
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | awk -F'/' '{print $3}')
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
          echo "Latest run_id: $RUN_ID"

      - name: Build Docker model
        working-directory: ./CI
        run: |
          mlflow models build-docker --model-uri "runs:/${{ steps.get_run_id.outputs.run_id }}/random_forest_final_model" --name sugarcane-model

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag and Push Docker Image
        run: |
          docker tag sugarcane-model ${{ secrets.DOCKER_HUB_USERNAME }}/sugarcane:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/sugarcane:latest
